# Generated by Django 6.1 on 2026-08-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openlibrary_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Open Library ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('autores', models.CharField(max_length=255, verbose_name='Autores')),
                ('capa_url', models.URLField(blank=True, max_length=500, verbose_name='URL da Capa')),
                ('isbn', models.CharField(blank=True, max_length=32, verbose_name='ISBN')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('assuntos', models.CharField(blank=True, max_length=500, verbose_name='Assuntos')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['-criado_em'],
            },
        ),
    ]
