# Generated by Django 6.1 on 2026-08-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='ano_publicacao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano de Publicação'),
        ),
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.CharField(blank=True, max_length=255, verbose_name='Editora'),
        ),
    ]
